Onglet commune
BaseAdresseNationale/bal-admin pull request #33
Opened 2023-07-17 12:26 UTC by fufeck

## Fonctionnalité

Ajouter l'onglet commune a bal-admin pour voir toutes les sources (mes adresses, le moissoneur, l'api-depot) pour une seule commune

2023-08-01 12:32 UTC, MaGOs92 requested changes
Je me demande si les autres onglets ont encore une utilité avec cette feature. En vrai on cherche toujours d'abord une commune et ensuite les sources / révisions.

2023-08-01 12:32 UTC, MaGOs92 commented on pages/communes/code/index.js
> +  const {code} = query
Je suis pas fan du nom de la route "/communes/code?code=37003". Pour moi, il faudrait plutôt avoir la route "/communes/37003". Pour faire ça, il faut nommer le fichier page avec le nom du param [codeCommune].jsx et le récupérer avec "const {codeCommune} = params"

2023-08-01 12:32 UTC, MaGOs92 commented on components/communes/moissoneur-list.js
> +  }, [code])
Si la data dépend que du code commune on peut la récupérer côté serveur non?

2023-08-01 12:32 UTC, MaGOs92 commented on components/communes/mes-adresses-list.js
> +  }, [code])
Même remarque, le top ça serait de fetch cette data côté serveur dans les getServerSideProps et de la passer en props à cette liste

2023-08-01 12:32 UTC, MaGOs92 commented on components/communes/api-depot-list.js
> +  }, [code])
Idem ici. D'ailleurs est-ce qu'il ne faudrait pas gérer la pagination côté serveur aussi? Je ne me rends pas bien compte si une commune peut avoir un très grand nombre de révisions

2023-08-02 07:00 UTC, fufeck commented on components/communes/mes-adresses-list.js
> +  }, [code])
Je m'étais fais la remarque mais `getServerSideProps` ne peut utiliser que sur un page. Donc sinon je charge tout sur la page [codeCommune].js et je passe tous au childs `MesAdresseList`, `MoissoneurList` et `ApiDepotList` mais je ne suis pas très fan. Une idée ?

2023-08-02 07:05 UTC, fufeck commented on components/communes/api-depot-list.js
> +  }, [code])
Pour le moment, il y a peu de révisions par commune, au grand maximum quelques dizaines. Si on refacto la route avec l'actuelle avec une query en plus comme suggérer dans https://github.com/BaseAdresseNationale/api-depot/pull/95 je préfère ne pas paginer la route /communes/:codeCommune/revisions qui est utilisé un peu partout

2023-08-02 07:34 UTC, fufeck commented on components/communes/moissoneur-list.js
> +  }, [code])
Je m'étais fais la remarque mais getServerSideProps ne peut utiliser que sur un page. Donc sinon je charge tout sur la page [codeCommune].js et je passe tous au childs MesAdresseList, MoissoneurList et ApiDepotList mais je ne suis pas très fan. Une idée ?

2023-08-02 07:49 UTC, MaGOs92 commented on components/communes/moissoneur-list.js
> +  }, [code])
Je pense que la bonne pratique ça serait plutôt de faire comme ça. Le top ça serait un composant List assez générique pour accepter une liste d'objets en props que ça soit des "MesAdresses, Moissonneur, ApiDepot...". Dans ma PR pour l'onglet partenaire j'ai créé un composant List générique, tu peux checker voir si ça conviendrait?

2023-08-03 12:36 UTC, MaGOs92 commented
Aussi autre point, je trouve ça un peu dommage de remettre une couche de JS alors que la migration Typescript arrive bientôt. Est-ce que ça vaudrait pas le coup d'attendre de passer le Ts en prod pour ne pas devoir refacto cet onglet plus tard?

2023-08-07 05:40 UTC, fufeck commented
> Aussi autre point, je trouve ça un peu dommage de remettre une couche de JS alors que la migration Typescript arrive bientôt. Est-ce que ça vaudrait pas le coup d'attendre de passer le Ts en prod pour ne pas devoir refacto cet onglet plus tard?

Ca me va, c'est pas urgent urgent, après j'espère juste que la migration de ts va pas juste créer trop de conflit avec cette PR

2023-09-01 13:22 UTC, MaGOs92 approved these changes
Tests and code LGTM

Je pense qu'on pourrait mettre cette onglet commune en premier à la place de "Mes adresses". A mon avis, il ne sert plus à rien avec cette PR. Il faudra demander à l'équipe ce qu'ils en pensent mardi

2023-09-04 08:16 UTC, merged